This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./Paper_EV.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Paper_EV.acn....done (65 entries accepted, 0 rejected).
Sorting entries....done (403 comparisons).
Generating output file Paper_EV.acr....done (32 lines written, 0 warnings).
Output written in Paper_EV.acr.
Transcript written in Paper_EV.alg.
